---
title: "no_tba_script"
output: html_document
date: "2024-03-14"
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
library(devtools)

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, 
                      message = FALSE, error = FALSE)

pad_pitdata <- function(pitdata, registered_teams){
  padders <- !(registered_teams %in% pitdata$Team.Number)
  pad <- data.frame(Timestamp = NA, Team.Number = padders, Weight = NA, 
                    Height = NA, Build.Quality. = NA, DriveType = NA)
  return(rbind(pitdata, pad))
}

theme_set(theme_bw())

```

```{r loading data}

scouted <- read.delim("data/greater_pittsburgh_data.txt")
pitdata <- read.delim("data/pitdatabuckeye.tsv")
colnames(scouted) <- tolower(colnames(scouted))

# typecasting
cast_chr_boolean <- function(chr){
    return(ifelse(chr %in% c("true", "True", "TRUE", "T", "1", "t"), 
                  TRUE, FALSE))
}

scouted$human_player_at_amp <- cast_chr_boolean(scouted$human_player_at_amp)
scouted$no_show <- cast_chr_boolean(scouted$no_show)
scouted$can_do_ground_pickup <- cast_chr_boolean(scouted$can_do_ground_pickup)
scouted$died <- cast_chr_boolean(scouted$died)
scouted$tipped_over <- cast_chr_boolean(scouted$tipped_over)

# retaining comments
comments <- scouted[, c("team_number", "scouter_initials", "x")]

# @TODO note cases where we missed a robot-match in the scouted data, and cases 
# where a team is in `scouted` but not in `tba_data` and output to file

scouted$total_notes <- scouted$auto_amp_scored + scouted$auto_speaker_scored + 
    scouted$tele_amp_scored + scouted$tele_speaker_scored + scouted$note_in_trap

scouted <- scouted %>%
    group_by(team_number) %>%
    summarize(auto_amp_score_avg = round(mean(auto_amp_scored), 2), 
              auto_amp_miss_avg = round(mean(auto_amp_missed), 2), 
              auto_spk_score_avg = round(mean(auto_speaker_scored), 2), 
              auto_spk_miss_avg = round(mean(auto_speaker_missed), 2), 
              tele_amp_score_avg = round(mean(tele_amp_scored), 2), 
              tele_amp_miss_avg = round(mean(tele_amp_missed), 2), 
              tele_spk_score_avg = round(mean(tele_speaker_scored), 2), 
              tele_spk_miss_avg = round(mean(tele_speaker_missed), 2), 
              trap_avg = round(mean(note_in_trap), 2), 
              avg_total_notes = round(mean(total_notes), 2),
              sd_total_notes = round(sd(total_notes), 2),
              hp_at_amp_pct = round(sum(human_player_at_amp) / n(), 2), 
              ground_pickup_pct = round(sum(can_do_ground_pickup) / n(), 2), 
              died_pct = round(sum(died) / n(), 2), 
              tip_pct = round(sum(tipped_over) / n(), 2), 
              no_show_pct = round(sum(no_show) / n(), 2)) %>%
    mutate(
        auto_amp_accuracy = round(auto_amp_score_avg / 
            (auto_amp_score_avg + auto_amp_miss_avg), 2), 
        auto_spk_accuracy = round(auto_spk_score_avg /
            (auto_spk_score_avg + auto_spk_miss_avg), 2),
        tele_amp_accuracy = round(tele_amp_score_avg / 
            (tele_amp_score_avg + tele_amp_miss_avg), 2), 
        tele_spk_accuracy = round(tele_spk_score_avg /
            (tele_spk_score_avg + tele_spk_miss_avg), 2)
    )


data <- merge(scouted, tba_data, by.x = "team_number", by.y = "id", 
              all.x = FALSE, all.y = TRUE)

data <- data %>%
    mutate(
        scouted_score = (auto_amp_score_avg * 2) + (auto_spk_score_avg * 5) + 
            (tele_amp_score_avg) + (tele_spk_score_avg * 2) + (trap_avg * 5) + 
            (auto_mobility_pct * 2) + 
            (endgame_onstage_pct * 3) + (endgame_park_pct), 
        trap_pts = trap_avg * 5, 
        onstage_pts = endgame_onstage_pct * 3, 
        park_pts = endgame_park_pct
    )

```

```{r}
red_alliance <- c(695, 3504, 2399)
blue_alliance <- c(4145, 4050, 4027)

red_df <- data[data$team_number %in% red_alliance, ]
red_pitdf <- pitdata[pitdata$Team.Number %in% red_alliance, ]
red_df$color <- "red"
blue_df <- data[data$team_number %in% blue_alliance, ]
blue_df$color <- "blue"
blue_pitdf <- pitdata[pitdata$Team.Number %in% blue_alliance, ]

viz <- rbind(red_df, blue_df)
viz$color <- factor(viz$color, 
                    levels = c("red", "blue"), labels = c("red", "blue"))

# example visualization
# other aesthetics to consider using: alpha (transparency), size
library(ggplot2)
library(gridExtra)
library(grid)
library(tidyverse)

#cooperitition
if (any(red_df == "3504") == TRUE) {
  if (sum(red_df$avg_total_notes)>15 & sum(red_df$avg_total_notes)<18 & sum(blue_df$tele_amp_score_avg > 1)) {
      print(paste("Cooperitition: Yes"))  
  }
  else {
    print(paste("Cooperitition: No"))  
  }
} 
if (any(blue_df == "3504"))
{
  if (sum(blue_df$avg_total_notes)>15 & sum(blue_df$avg_total_notes)<18 & sum(red_df$tele_amp_score_avg > 1)) 
  {
      print(paste("Cooperitition: Yes"))  
  } else {
    print(paste("Cooperitition: No"))  
  }
}

#prints stats about all teams -> FINISHED!!!! 
print(paste("BLUE ALLIANCE"))

set_flextable_defaults(
font.family = "Arial", font.size = 8, border.color = "#0066B3",
padding = 6, background.color = "#EFEFEF")
vizBlueDf <- data.frame("Team?" = blue_df$team_number,
"scouted_score" = blue_df$scouted_score, "Drive?" = blue_pitdf$DriveType, "Amp %" = blue_df$tele_amp_accuracy, "Can climb" = (blue_df$endgame_onstage_pct>0), "Under stage?" = (blue_pitdf$Height < 29), "Speaker %" = blue_df$tele_spk_accuracy, "IntakesFromGround?" = blue_pitdf$Ground_Pickup, "ShootsAwayFromSubwoofer" = blue_pitdf$Can_shoot_away_from_subwoofer)

#Change the pitdata stuff to stuff collected by scouters

flextable(vizBlueDf)


print(paste("RED ALLIANCE"))
library(flextable)

set_flextable_defaults(
font.family = "Arial", font.size = 8, border.color = "#e5383b",
padding = 6, background.color = "#EFEFEF")
vizRedDf <- data.frame("Team?" = red_df$team_number,
"scouted_score" = red_df$scouted_score, "Drive?" = red_pitdf$DriveType, "Amp %" = red_df$tele_amp_accuracy, "Can climb" = (red_df$endgame_onstage_pct>0), "Under stage?" = (red_pitdf$Height < 29), "Speaker %" = red_df$tele_spk_accuracy, "IntakesFromGround?" = red_pitdf$Ground_Pickup, "ShootsAwayFromSubwoofer" = red_pitdf$Can_shoot_away_from_subwoofer)

#Change the pitdata stuff in a pit

flextable(vizRedDf)

# Total notes/scouted score
ggplot(viz, 
       aes(x = avg_total_notes, y = scouted_score, 
           label = team_number, color = color)) + 
    geom_label() + 
    labs(title = "Match at-a-glance", 
         color = "Alliance")

# Endgame

# We use the pts version of each variable so that each task is weighted by 
# the number of points it scores.
ggplot(gather(viz, key = "key", value = "value", 
              trap_pts, onstage_pts), 
       aes(x = factor(paste(team_number, color, sep = "\n")), y = value, fill = key)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Endgame Scoring", x = "Team", y = "Scoring")

# Weighting doesn't matter for Melody contribution so we don't need to do the
# same here.
ggplot(gather(viz, key = "key", value = "value", 
              auto_amp_score_avg, tele_amp_score_avg, 
              auto_spk_score_avg, tele_spk_score_avg), 
       aes(x = factor(paste(team_number, color, sep = "\n")), y = value, fill = key)) + 
  geom_bar(stat = "identity") + 
  labs(title = "Melody Contribution", x = "Team", y = "# Notes")
```
