---
title: "champs_reporter"
author: "Girls of Steel Scouting"
date: "2024-04-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, message = FALSE, include = FALSE}
# setting include = FALSE so that the file knits without internet
library(devtools)
load_all("../tbaR")
source("statbotics_readR.R")

event_code <- "2024new"

registered_teams <- event_teams(event_code, keys = TRUE)
registered_teams <- as.numeric(
    substr(registered_teams, 4, nchar(registered_teams))
)

statbotics_data <- data.frame(
    t(sapply(registered_teams, read_team_year, year = 2024))
)

save(statbotics_data, registered_teams, event_code, file = "data/setup.rda")
```

Suggestion from Reinhart: 
use `vec_rbind` from `vctrs` to bind together the dataframes

```{r, message = FALSE, error = FALSE, warning = FALSE, include = FALSE}
# gabriel's guided tour of historical matches

# fundamentally, we want to mitigate API risk by looking at historical matches
# as well as matches at the championship.

# @TODO gotta make better names for everything, but this is the code outline

# explain additional parameters through "..."
all_2024_matches <- lapply(registered_teams, team_matches, year = 2024)

# why are these not all the same?
sapply(all_2024_matches, ncol)

# answer: check this output (last column)
tmp <- merge(all_2024_matches[[4]], all_2024_matches[[1]], all = TRUE)

result <- all_2024_matches %>%
    reduce(full_join)

# do we need to trim possibly-duplicate rows (i.e. if two teams were in the same match?)
stopifnot(!any(duplicated(result)))

year_historical_matches <- function(event_code){
    registered_teams <- event_teams(event_code, keys = TRUE)
    registered_teams <- as.numeric(
        substr(registered_teams, 4, nchar(registered_teams))
    )
    year <- as.numeric(substr(event_code, 1, 4))
    matches <- sapply(registered_teams, team_matches, year = year)
    result <- matches %>%
        reduce(full_join)
    # check for duplicated matches
    stopifnot(!any(duplicated(result)))
    return(result)
}

data <- get_multifield_df(year_historical_matches("2024gaalb"), 
                          c("autoLine", "endGame"))

data$id <- as.numeric(
    substr(data$id, 4, nchar(data$id))
)

data <- data[data$id %in% registered_teams, ]

data <- merge(data, statbotics_data, by.x = "id", by.y = "team")
```

```{r}
```

```{r team view, include = FALSE}

```

```{r}
load("data/setup.rda")
matchdata <- read_csv("data/2024newton_match.csv", show_col_types = FALSE)
matchdata$tele_total_notes <- matchdata$tele_speaker_score + 
    matchdata$tele_amp_score + matchdata$feed_count

red_alliance <- c(4779, 3504, 3339)
blue_alliance <- c(58, 254, 9475)

alliance <- ifelse(3504 %in% red_alliance, red_alliance, blue_alliance)

important_cols <- c(
    "team_id", "auto_speaker_score", "tele_speaker_score", "tele_amp_score", 
    "tele_total_notes", "feed_count", "trap_note_score", "stage_onstage", 
    "harmony_success"
)

p1 <- matchdata[matchdata$team_id %in% 4779, important_cols]
p2 <- matchdata[matchdata$team_id %in% 3504, important_cols]
p3 <- matchdata[matchdata$team_id %in% 3339, important_cols]

View(p1)
View(p2)
View(p3)

matchdata <- matchdata %>%
    group_by(team_id) %>%
    summarize(
        avg_tele_total_notes = mean(tele_total_notes, na.rm = TRUE), 
        avg_tele_spk = mean(tele_speaker_score, na.rm = TRUE), 
        avg_tele_amp = mean(tele_amp_score, na.rm = TRUE),
        avg_feed = mean(feed_count, na.rm = TRUE),
        auto_avg = mean(auto_speaker_score, na.rm = TRUE), 
        foul_avg = mean(foul_count, na.rm = TRUE), 
        trap_avg = mean(trap_note_score, na.rm = TRUE), 
        harmony_pct = sum(harmony_success, na.rm = TRUE) / 
            (sum(harmony_success, na.rm = TRUE) + 
                 sum(harmony_attempt_failed, na.rm = TRUE)), 
        onstage_avg = (mean(harmony_success, na.rm = TRUE) + mean(stage_onstage, na.rm = TRUE))
    )

red_df <- matchdata[matchdata$team_id %in% red_alliance, ]
red_df$color <- "red"
blue_df <- matchdata[matchdata$team_id %in% blue_alliance, ]
blue_df$color <- "blue"

viz <- rbind(red_df, blue_df)

ggplot(viz, 
       aes(x = avg_tele_total_notes, y = auto_avg, 
           label = team_id, color = color)) + 
    geom_label() + 
    labs(title = "Match at-a-glance", 
         color = "Alliance", x = "Teleop Throughput", y = "Auto Speaker Score")

ggplot(viz, aes(x = avg_feed, y = avg_tele_spk + avg_tele_amp, 
                label = team_id, color = color)) + 
    geom_label() + 
    labs(title = "Scores vs Feeds", 
         color = "Alliance", x = "Feeding Average", y = "Average # Notes Scored")
```

