---
title: "picklist_generator"
output: pdf_document
date: "2024-03-14"
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
library(devtools)
load_all("../tbaR")

event_code <- "2024ohcl" 
registered_teams <- event_teams(event_code, keys = TRUE)
registered_teams <- as.numeric(substr(registered_teams, 4, 
                                      nchar(registered_teams)))

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, 
                      message = FALSE, error = FALSE)

pad_pitdata <- function(pitdata, registered_teams){
  padders <- !(registered_teams %in% pitdata$Team.Number)
  pad <- data.frame(Timestamp = NA, Team.Number = padders, Weight = NA, 
                    Height = NA, Build.Quality. = NA, DriveType = NA)
  return(rbind(pitdata, pad))
}

theme_set(theme_bw())

tba_matches <- event_matches(event_code)
tba_data <- get_multifield_df(tba_matches, 
                              fields = c("autoLine", "endGame"))

tba_data$id <- as.numeric(substr(tba_data$id, 4, nchar(tba_data$id)))
tba_data$n_matches <- tba_data$autoLine.Yes + tba_data$autoLine.No
tba_data <- tba_data %>%
    mutate(auto_mobility_pct = round(autoLine.Yes / n_matches, 2), 
           endgame_park_pct = round(endGame.Parked / n_matches, 2), 
           endgame_onstage_pct = round(
               (endGame.CenterStage + endGame.StageLeft + endGame.StageRight) /
                   n_matches, 2), 
           endgame_none_pct = round(endGame.None / n_matches, 2)
           ) %>%
    select(
        "id", "auto_mobility_pct", "endgame_park_pct", 
        "endgame_onstage_pct", "endgame_none_pct"
    )

scouted <- read.delim("data/greater_pittsburgh_data.txt")
pitdata <- read.delim("data/pitdata.tsv")
colnames(scouted) <- tolower(colnames(scouted))

# typecasting
cast_chr_boolean <- function(chr){
    return(ifelse(chr %in% c("true", "True", "TRUE", "T", "1", "t"), 
                  TRUE, FALSE))
}

scouted$human_player_at_amp <- cast_chr_boolean(scouted$human_player_at_amp)
scouted$no_show <- cast_chr_boolean(scouted$no_show)
scouted$can_do_ground_pickup <- cast_chr_boolean(scouted$can_do_ground_pickup)
scouted$died <- cast_chr_boolean(scouted$died)
scouted$tipped_over <- cast_chr_boolean(scouted$tipped_over)

# retaining comments
comments <- scouted[, c("team_number", "scouter_initials", "x")]

# @TODO note cases where we missed a robot-match in the scouted data, and cases 
# where a team is in `scouted` but not in `tba_data` and output to file

scouted$total_notes <- scouted$auto_amp_scored + scouted$auto_speaker_scored + 
    scouted$tele_amp_scored + scouted$tele_speaker_scored + scouted$note_in_trap

scouted <- scouted %>%
    group_by(team_number) %>%
    summarize(auto_amp_score_avg = round(mean(auto_amp_scored), 2), 
              auto_amp_miss_avg = round(mean(auto_amp_missed), 2), 
              auto_spk_score_avg = round(mean(auto_speaker_scored), 2), 
              auto_spk_miss_avg = round(mean(auto_speaker_missed), 2), 
              tele_amp_score_avg = round(mean(tele_amp_scored), 2), 
              tele_amp_miss_avg = round(mean(tele_amp_missed), 2), 
              tele_spk_score_avg = round(mean(tele_speaker_scored), 2), 
              tele_spk_miss_avg = round(mean(tele_speaker_missed), 2), 
              trap_avg = round(mean(note_in_trap), 2), 
              avg_total_notes = round(mean(total_notes), 2),
              sd_total_notes = round(sd(total_notes), 2),
              hp_at_amp_pct = round(sum(human_player_at_amp) / n(), 2), 
              ground_pickup_pct = round(sum(can_do_ground_pickup) / n(), 2), 
              died_pct = round(sum(died) / n(), 2), 
              tip_pct = round(sum(tipped_over) / n(), 2), 
              no_show_pct = round(sum(no_show) / n(), 2)) %>%
    mutate(
        auto_amp_accuracy = round(auto_amp_score_avg / 
            (auto_amp_score_avg + auto_amp_miss_avg), 2), 
        auto_spk_accuracy = round(auto_spk_score_avg /
            (auto_spk_score_avg + auto_spk_miss_avg), 2),
        tele_amp_accuracy = round(tele_amp_score_avg / 
            (tele_amp_score_avg + tele_amp_miss_avg), 2), 
        tele_spk_accuracy = round(tele_spk_score_avg /
            (tele_spk_score_avg + tele_spk_miss_avg), 2)
    )


data <- merge(scouted, tba_data, by.x = "team_number", by.y = "id", 
              all.x = FALSE, all.y = TRUE)

data <- data %>%
    mutate(
        scouted_score = (auto_amp_score_avg * 2) + (auto_spk_score_avg * 5) + 
            (tele_amp_score_avg * 2.5) + (tele_spk_score_avg * 2.5) + 
          (trap_avg * 5) + (auto_mobility_pct * 2) + 
          (endgame_onstage_pct * 3) + (endgame_park_pct), 
        trap_pts = trap_avg * 5, 
        onstage_pts = endgame_onstage_pct * 3, 
        park_pts = endgame_park_pct
    )

```

picklist rationale!:
categories to be able to generate a good team for either scenario

what do teams actually pick for?:
- being able to trap!
- speaker/amp ability
- standard deviation
- Auto Compatibility -> when choosing amongst top teams
```{r}
#Create a list of teams for all variables selected
library(flextable)
top_score <- data[order(data$scouted_score, decreasing = TRUE), ]

set_flextable_defaults(
font.family = "Arial", font.size = 10, border.color = "#e5383b",
padding = 10, background.color = "#EFEFEF")
viz <- data.frame("team_number" = top_score$team_number,
"scouted_score" = top_score$scouted_score)
flextable(viz)


```