---
title: "GoS Scouting Report"
author: "Girls of Steel"
date: "2024-02-22"
output: pdf_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
library(devtools)
load_all("../tbaR")

event_code <- "2024paca" #change this to 2024ohcl Thursday
registered_teams <- event_teams(event_code, keys = TRUE)
registered_teams <- as.numeric(substr(registered_teams, 4, 
                                      nchar(registered_teams)))

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, 
                      message = FALSE, error = FALSE)

pad_pitdata <- function(pitdata, registered_teams){
  padders <- !(registered_teams %in% pitdata$Team.Number)
  pad <- data.frame(Timestamp = NA, Team.Number = padders, Weight = NA, 
                    Height = NA, Build.Quality. = NA, DriveType = NA)
  return(rbind(pitdata, pad))
}

theme_set(theme_bw())

tba_matches <- event_matches(event_code)
tba_data <- get_multifield_df(tba_matches, 
                              fields = c("autoLine", "endGame"))
```

```{r loading data}
tba_data$id <- as.numeric(substr(tba_data$id, 4, nchar(tba_data$id)))
tba_data$n_matches <- tba_data$autoLine.Yes + tba_data$autoLine.No
tba_data <- tba_data %>%
    mutate(auto_mobility_pct = round(autoLine.Yes / n_matches, 2), 
           endgame_park_pct = round(endGame.Parked / n_matches, 2), 
           endgame_onstage_pct = round(
               (endGame.CenterStage + endGame.StageLeft + endGame.StageRight) /
                   n_matches, 2), 
           endgame_none_pct = round(endGame.None / n_matches, 2)
           ) %>%
    select(
        "id", "auto_mobility_pct", "endgame_park_pct", 
        "endgame_onstage_pct", "endgame_none_pct"
    )

scouted <- read.delim("data/greater_pittsburgh_data.txt")
pitdata <- read.delim("data/pitdata.tsv")
autoData <- read.delim("data/autoCenterlineData.txt")
colnames(scouted) <- tolower(colnames(scouted))

# typecasting
cast_chr_boolean <- function(chr){
    return(ifelse(chr %in% c("true", "True", "TRUE", "T", "1", "t"), 
                  TRUE, FALSE))
}

scouted$human_player_at_amp <- cast_chr_boolean(scouted$human_player_at_amp)
scouted$no_show <- cast_chr_boolean(scouted$no_show)
scouted$can_do_ground_pickup <- cast_chr_boolean(scouted$can_do_ground_pickup)
scouted$died <- cast_chr_boolean(scouted$died)
scouted$tipped_over <- cast_chr_boolean(scouted$tipped_over)

# retaining comments
comments <- scouted[, c("team_number", "scouter_initials", "x")]

# @TODO note cases where we missed a robot-match in the scouted data, and cases 
# where a team is in `scouted` but not in `tba_data` and output to file

scouted$total_notes <- scouted$auto_amp_scored + scouted$auto_speaker_scored + 
    scouted$tele_amp_scored + scouted$tele_speaker_scored + scouted$note_in_trap

scouted <- scouted %>%
    group_by(team_number) %>%
    summarize(auto_amp_score_avg = round(mean(auto_amp_scored), 2), 
              auto_amp_miss_avg = round(mean(auto_amp_missed), 2), 
              auto_spk_score_avg = round(mean(auto_speaker_scored), 2), 
              auto_spk_miss_avg = round(mean(auto_speaker_missed), 2), 
              tele_amp_score_avg = round(mean(tele_amp_scored), 2), 
              tele_amp_miss_avg = round(mean(tele_amp_missed), 2), 
              tele_spk_score_avg = round(mean(tele_speaker_scored), 2), 
              tele_spk_miss_avg = round(mean(tele_speaker_missed), 2), 
              trap_avg = round(mean(note_in_trap), 2), 
              avg_total_notes = round(mean(total_notes), 2),
              sd_total_notes = round(sd(total_notes), 2),
              hp_at_amp_pct = round(sum(human_player_at_amp) / n(), 2), 
              ground_pickup_pct = round(sum(can_do_ground_pickup) / n(), 2), 
              died_pct = round(sum(died) / n(), 2), 
              tip_pct = round(sum(tipped_over) / n(), 2), 
              no_show_pct = round(sum(no_show) / n(), 2)) %>%
    mutate(
        auto_amp_accuracy = round(auto_amp_score_avg / 
            (auto_amp_score_avg + auto_amp_miss_avg), 2), 
        auto_spk_accuracy = round(auto_spk_score_avg /
            (auto_spk_score_avg + auto_spk_miss_avg), 2),
        tele_amp_accuracy = round(tele_amp_score_avg / 
            (tele_amp_score_avg + tele_amp_miss_avg), 2), 
        tele_spk_accuracy = round(tele_spk_score_avg /
            (tele_spk_score_avg + tele_spk_miss_avg), 2)
    )


data <- merge(scouted, tba_data, by.x = "team_number", by.y = "id", 
              all.x = FALSE, all.y = TRUE)

data <- data %>%
    mutate(
        scouted_score = (auto_amp_score_avg * 2) + (auto_spk_score_avg * 5) + 
            (tele_amp_score_avg) + (tele_spk_score_avg * 2) + (trap_avg * 5) + 
            (auto_mobility_pct * 2) + 
            (endgame_onstage_pct * 3) + (endgame_park_pct), 
        trap_pts = trap_avg * 5, 
        onstage_pts = endgame_onstage_pct * 3, 
        park_pts = endgame_park_pct
    )

```

```{r}
red_alliance <- c(3015, 1559, 578)
blue_alliance <- c(4145, 144, 340)

red_df <- data[data$team_number %in% red_alliance, ]
red_pitdf <- pitdata[pitdata$Team.Number %in% red_alliance, ]
red_df$color <- "red"
blue_df <- data[data$team_number %in% blue_alliance, ]
blue_df$color <- "blue"

viz <- rbind(red_df, blue_df)
viz$color <- factor(viz$color, 
                    levels = c("red", "blue"), labels = c("red", "blue"))

# example visualization
# other aesthetics to consider using: alpha (transparency), size
library(ggplot2)
library(gridExtra)
library(grid)
library(tidyverse)

#cooperitition
if (any(red_df == "3504") == TRUE) {
  if (sum(red_df$avg_total_notes)>15 & sum(red_df$avg_total_notes)<18 & sum(blue_df$tele_amp_score_avg > 1)) {
      print(paste("Cooperitition: Yes"))  
  }
  else {
    print(paste("Cooperitition: Yes"))  
  }
} 
if (any(blue_df == "3504"))
{
  if (sum(blue_df$avg_total_notes)>15 & sum(blue_df$avg_total_notes)<18 & sum(red_df$tele_amp_score_avg > 1)) 
  {
      print(paste("Cooperitition: Yes"))  
  } else {
    print(paste("Cooperitition: Yes"))  
  }
}

#prints stats about all teams -> UNFINISHED!!!! 
print(paste("BLUE ALLIANCE"))
for (x in blue_df[,1])
{
  #more printlines coming! but i am optimizing them (maybe dont incluide opposing 
  #alliance? unsure)
  
}

library(flextable)

set_flextable_defaults(
font.family = "Arial", font.size = 10, border.color = "#e5383b",
padding = 10, background.color = "#EFEFEF")
vizRedDf <- data.frame("Team?" = red_df$team_number,
"scouted_score" = red_df$scouted_score, "Drive?" = red_pitdf$DriveType, "Amp %" = red_df$tele_amp_accuracy, "Speaker %" = red_df$tele_spk_accuracy, "Can climb" = (red_df$endgame_onstage_pct>0))

flextable(vizRedDf)

temp = comments[comments$team_number == "8705", ]

# Total notes/scouted score
ggplot(viz, 
       aes(x = avg_total_notes, y = scouted_score, 
           label = team_number, color = color)) + 
    geom_label() + 
    labs(title = "Match at-a-glance", 
         color = "Alliance")

# Endgame

f <- ifelse(viz$color == "red", "red", "blue")

# We use the pts version of each variable so that each task is weighted by 
# the number of points it scores.
ggplot(gather(viz, key = "key", value = "value", 
              trap_pts, onstage_pts, park_pts), 
       aes(x = factor(paste(team_number, color, sep = "\n")), y = value, fill = key)) + 
  geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(colour = f)) +
  labs(title = "Endgame Scoring", x = "Team", y = "Scoring")

# Weighting doesn't matter for Melody contribution so we don't need to do the
# same here.
ggplot(gather(viz, key = "key", value = "value", 
              auto_amp_score_avg, tele_amp_score_avg, 
              auto_spk_score_avg, tele_spk_score_avg), 
       aes(x = factor(paste(team_number, color, sep = "\n")), y = value, fill = key)) + 
  geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(colour = f)) +
  labs(title = "Melody Contribution", x = "Team", y = "# Notes")
```

```{r}

vizCombined <- viz %>%
    group_by(color) %>%
    summarize(auto_amp_score_avg = sum(auto_amp_score_avg), 
              tele_amp_score_avg = sum(tele_amp_score_avg), 
              auto_spk_score_avg = sum(auto_spk_score_avg), 
              tele_spk_score_avg = sum(tele_spk_score_avg))

f <- ifelse(vizCombined$color == "red", "red", "blue")

ggplot(gather(vizCombined, key = "key", value = "value", 
              auto_amp_score_avg, tele_amp_score_avg, 
              auto_spk_score_avg, tele_spk_score_avg), 
       aes(x = factor(paste(color)), y = value, fill = key)) + 
  geom_bar(stat = "identity", width = 0.40) + 
    theme(axis.text.x = element_text(colour = f)) +
  labs(title = "Combined Melody Contribution", x = "Team", y = "# Notes")

```

```{r}

new_harmonyDF <- tba_matches[, c("match_number", "comp_level", "blue1", "blue2", "blue3", "blue_endGameRobot1", "blue_endGameRobot2", "blue_endGameRobot3", 
                                 "red1", "red2", "red3", "red_endGameRobot1", "red_endGameRobot2", "red_endGameRobot3")]
#new_harmonyDF <- viz[, c("trap_pts")]

new_harmonyDF <- new_harmonyDF %>%
    mutate(
        blue1 = as.integer(substr(blue1, 4, nchar(blue1))),
        blue2 = as.integer(substr(blue2, 4, nchar(blue2))),
        blue3 = as.integer(substr(blue3, 4, nchar(blue3))),
        red1 = as.integer(substr(red1, 4, nchar(red1))),
        red2 = as.integer(substr(red2, 4, nchar(red2))),
        red3 = as.integer(substr(red3, 4, nchar(red3)))
    )

for (i in 1:nrow(new_harmonyDF)){
  if (is.na(new_harmonyDF[i, "blue_endGameRobot1"])){
    message(is.na(new_harmonyDF[i, "blue_endGameRobot1"]))
    new_harmonyDF <- new_harmonyDF[-c(i), ]
  }
}

blue1 = vector(, nrow(new_harmonyDF))
blue2 = vector(, nrow(new_harmonyDF))
blue3 = vector(, nrow(new_harmonyDF))
red1 = vector(, nrow(new_harmonyDF))
red2 = vector(, nrow(new_harmonyDF))
red3 = vector(, nrow(new_harmonyDF))

for (i in 1:nrow(new_harmonyDF)){
  if (new_harmonyDF[i, "blue_endGameRobot1"] == "None"){
    blue1[i] = "None"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot1"] == "Parked"){
    blue1[i] = "Parked"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot1"] == new_harmonyDF[i, "blue_endGameRobot2"] && 
           new_harmonyDF[i, "blue_endGameRobot2"] == new_harmonyDF[i, "blue_endGameRobot3"]){
    blue1[i] = "DoubleHarmony"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot1"] == new_harmonyDF[i, "blue_endGameRobot2"] || 
           new_harmonyDF[i, "blue_endGameRobot1"] == new_harmonyDF[i, "blue_endGameRobot3"]){
    blue1[i] = "SingleHarmony"
  }
  else{
    blue1[i] = "HungAlone"
  }
  
  
  if (new_harmonyDF[i, "blue_endGameRobot2"] == "None"){
    blue2[i] = "None"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot2"] == "Parked"){
    blue2[i] = "Parked"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot1"] == new_harmonyDF[i, "blue_endGameRobot2"] && 
           new_harmonyDF[i, "blue_endGameRobot2"] == new_harmonyDF[i, "blue_endGameRobot3"]){
    blue2[i] = "DoubleHarmony"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot2"] == new_harmonyDF[i, "blue_endGameRobot1"] || 
           new_harmonyDF[i, "blue_endGameRobot2"] == new_harmonyDF[i, "blue_endGameRobot3"]){
    blue2[i] = "SingleHarmony"
  }
  else{
    blue2[i] = "HungAlone"
  }
  
  if (new_harmonyDF[i, "blue_endGameRobot3"] == "None"){
    blue3[i] = "None"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot3"] == "Parked"){
    blue3[i] = "Parked"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot1"] == new_harmonyDF[i, "blue_endGameRobot2"] && 
           new_harmonyDF[i, "blue_endGameRobot2"] == new_harmonyDF[i, "blue_endGameRobot3"]){
    blue3[i] = "DoubleHarmony"
  }
  else if (new_harmonyDF[i, "blue_endGameRobot3"] == new_harmonyDF[i, "blue_endGameRobot1"] || 
           new_harmonyDF[i, "blue_endGameRobot3"] == new_harmonyDF[i, "blue_endGameRobot2"]){
    blue3[i] = "SingleHarmony"
  }
  else{
    blue3[i] = "HungAlone"
  }
  
  
  if (new_harmonyDF[i, "red_endGameRobot1"] == "None"){
    red1[i] = "None"
  }
  else if (new_harmonyDF[i, "red_endGameRobot1"] == "Parked"){
    red1[i] = "Parked"
  }
  else if (new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot2"] && 
           new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot3"]){
    red1[i] = "DoubleHarmony"
  }
  else if (new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot2"] || 
           new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot3"]){
    red1[i] = "SingleHarmony"
  }
  else{
    red1[i] = "HungAlone"
  }
  
  if (new_harmonyDF[i, "red_endGameRobot2"] == "None"){
    red2[i] = "None"
  }
  else if (new_harmonyDF[i, "red_endGameRobot2"] == "Parked"){
    red2[i] = "Parked"
  }
  else if (new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot2"] && 
           new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot3"]){
    red2[i] = "DoubleHarmony"
  }
  else if (new_harmonyDF[i, "red_endGameRobot2"] == new_harmonyDF[i, "red_endGameRobot1"] || 
           new_harmonyDF[i, "red_endGameRobot2"] == new_harmonyDF[i, "red_endGameRobot3"]){
    red2[i] = "SingleHarmony"
  }
  else{
    red2[i] = "HungAlone"
  }
  
  if (new_harmonyDF[i, "red_endGameRobot3"] == "None"){
    red3[i] = "None"
  }
  else if (new_harmonyDF[i, "red_endGameRobot3"] == "Parked"){
    red3[i] = "Parked"
  }
  else if (new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot2"] && 
           new_harmonyDF[i, "red_endGameRobot1"] == new_harmonyDF[i, "red_endGameRobot3"]){
    red3[i] = "DoubleHarmony"
  }
  else if (new_harmonyDF[i, "red_endGameRobot3"] == new_harmonyDF[i, "red_endGameRobot1"] || 
           new_harmonyDF[i, "red_endGameRobot3"] == new_harmonyDF[i, "red_endGameRobot2"]){
    red3[i] = "SingleHarmony"
  }
  else{
    red3[i] = "HungAlone"
  }
 
}
 
new_harmonyDF$blue1post <- blue1
new_harmonyDF$blue2post <- blue2
new_harmonyDF$blue3post <- blue3
new_harmonyDF$red1post <- red1
new_harmonyDF$red2post <- red1
new_harmonyDF$red3post <- red3
 

postProHarmonyDF <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c("teamNum", "matchNum", "matchType", "endgamePos")
colnames(postProHarmonyDF) <- x
#postProHarmonyDF <- data.frame(Column1 = "Team Number", Column2 = "Endgame")

for (i in 1:nrow(new_harmonyDF)) {
  if (!is.na(new_harmonyDF[i, "blue_endGameRobot1"])){
      postProHarmonyDF[nrow(postProHarmonyDF) + 1,] = c(new_harmonyDF[i, "blue1"], new_harmonyDF[i, "match_number"], 
                                                        new_harmonyDF[i, "comp_level"], new_harmonyDF[i, "blue1post"])
      postProHarmonyDF[nrow(postProHarmonyDF) + 1,] = c(new_harmonyDF[i, "blue2"], new_harmonyDF[i, "match_number"], 
                                                        new_harmonyDF[i, "comp_level"], new_harmonyDF[i, "blue2post"])
     postProHarmonyDF[nrow(postProHarmonyDF) + 1,] = c(new_harmonyDF[i, "blue3"], new_harmonyDF[i, "match_number"], 
                                                        new_harmonyDF[i, "comp_level"], new_harmonyDF[i, "blue3post"])
     postProHarmonyDF[nrow(postProHarmonyDF) + 1,] = c(new_harmonyDF[i, "red1"], new_harmonyDF[i, "match_number"], 
                                                        new_harmonyDF[i, "comp_level"], new_harmonyDF[i, "red1post"])
     postProHarmonyDF[nrow(postProHarmonyDF) + 1,] = c(new_harmonyDF[i, "red2"], new_harmonyDF[i, "match_number"], 
                                                        new_harmonyDF[i, "comp_level"], new_harmonyDF[i, "red2post"])
     postProHarmonyDF[nrow(postProHarmonyDF) + 1,] = c(new_harmonyDF[i, "red3"], new_harmonyDF[i, "match_number"], 
                                                        new_harmonyDF[i, "comp_level"], new_harmonyDF[i, "red3post"])
  }
}

graphHarmonyDF <- data.frame(matrix(ncol = 4, nrow = 0))
x <- c("teamNum", "matchNum", "matchType", "endgamePos")
colnames(graphHarmonyDF) <- x

vizTeamsList <- unique(viz$team_number)

summaryHarmonyDF <- data.frame(matrix(ncol = 7, nrow = 0))
x <- c("teamNum", "None", "Parked", "HungAlone", "SingleHarmony", "DoubleHarmony", "Color")
colnames(summaryHarmonyDF) <- x

for (j in 1:length(vizTeamsList)){ 
  selectedTeam <- vizTeamsList[j]
  numNone <- 0
  numParked <- 0
  numHungAlone <- 0
  numSingleHarmony <- 0
  numDoubleHarmony <- 0
  color <- NULL
  for (i in 1:nrow(postProHarmonyDF)) {
    if (postProHarmonyDF[i, "teamNum"] == selectedTeam){ 
      graphHarmonyDF <- rbind(graphHarmonyDF, postProHarmonyDF[i,])
      
      if (postProHarmonyDF[i, "endgamePos"] == "None"){
        numNone <- numNone + 1
      }
      
      else if (postProHarmonyDF[i, "endgamePos"] == "Parked"){
        numParked <- numParked + 1
      }
      
      else if (postProHarmonyDF[i, "endgamePos"] == "HungAlone"){
        numHungAlone <- numHungAlone + 1
      }
      
      else if (postProHarmonyDF[i, "endgamePos"] == "SingleHarmony"){
        numSingleHarmony <- numSingleHarmony + 1
      }
      
      else if (postProHarmonyDF[i, "endgamePos"] == "DoubleHarmony"){
        numDoubleHarmony <- numDoubleHarmony + 1
      }
      
      if (selectedTeam %in% red_df$team_number) {
        color = "red"
      }
      else {
        color = "blue"
      }
    }
    
  }
  summaryHarmonyDF <- rbind(summaryHarmonyDF, list(selectedTeam, numNone, numParked, numHungAlone, numSingleHarmony, numDoubleHarmony, color))
}

x <- c("teamNum", "None", "Parked", "HungAlone", "SingleHarmony", "DoubleHarmony", "Color")
colnames(summaryHarmonyDF) <- x
``` 

```{r}
f <- ifelse(summaryHarmonyDF$Color == "red", "red", "blue")

ggplot(gather(summaryHarmonyDF, key = "key", value = "value", 
              None, Parked, 
              HungAlone, SingleHarmony, DoubleHarmony), 
       aes(x = factor(paste(teamNum, Color, sep = "\n")), y = value, fill = key)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(colour = f)) +
  labs(title = "Harmony Contribution", x = "Team", y = "# Occurences")

```

```{r}

autoData[autoData$TeamNum==325 & autoData$Note == 7,] 

```
